language: php

php:
    - 7.1
    - 7.3

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE
        
matrix:
  fast_finish: true

  include:
  - php: 7.1
    env: PREFER_LOWEST=1

before_install:
    - phpenv config-add ci/travis.php.ini

install:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --no-interaction; fi;
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --no-interaction --prefer-dist --prefer-stable; fi;
  - if [[ $PREFER_LOWEST == 1 ]]; then composer require --dev dereuromark/composer-prefer-lowest; fi
 
script:
    - composer cs-check
    - if [[ $PREFER_LOWEST == 1 ]]; then vendor/bin/validate-prefer-lowest; fi

after_success:
    - vendor/bin/coveralls -vvv

notifications:
    email: false
